/*################  AUTH ###############*/
export const LOGIN_USER="LOGIN_USER"
export const REGISTER="REGISTER"
export const GET_AUTH_USER="GET_AUTH_USER"
export const AUTH_ERROR="AUTH_ERROR"
export const LOGOUT_USER="LOGOUT_USER"
export const SET_LOADING="SET_LOADING"
export const EDIT_USER="EDIT_USER"
export const RESET_ERROR="RESET_ERROR"
export const RESET_MESSAGE="RESET_MESSAGE"
/*################  ATELIER ###############*/

export const GET_ATELIER="GET_ATELIER"
export const ADD_ATELIER="ADD_ATELIER"
export const GET_ALL_ATELIER="GET_ALL_ATELIER"
export const DELETE_ATELIER="DELETE_ATELIER"
export const UPDATE_ATELIER="UPDATE_ATELIER"
export const MAKE_PARTNER="MAKE_PARTNER"
export const UNMAKE_PARTNER="UNMAKE_PARTNER"

/*################  USER ###############*/

export const GET_USER="GET_USER"
export const ADD_USER="ADD_USER"
export const GET_ALL_USER="GET_ALL_USER"
export const BLOCK_USER="BLOCK_USER"
export const UNBLOCK_USER="UNBLOCK_USER"
export const UPDATE_USER="UPDATE_USER"

/*################  DEMANDES ###############*/

export const GET_DEMANDE="GET_DEMANDE"
export const GET_USER_DEMANDE="GET_USER_DEMANDE"
export const ADD_DEMANDE="ADD_DEMANDE"
export const GET_ALL_DEMANDE="GET_ALL_DEMANDE"
export const DELETE_DEMANDE="DELETE_DEMANDE"
export const UPDATE_DEMANDE="UPDATE_DEMANDE"

/*################  RESERVATION ###############*/
export const GET_USER_RESERVATION="GET_USER_RESERVATION"
export const GET_RESERVATION="GET_RESERVATION"
export const ADD_RESERVATION="ADD_RESERVATION"
export const GET_ALL_RESERVATION="GET_ALL_RESERVATION"
export const DELETE_RESERVATION="DELETE_RESERVATION"
export const UPDATE_RESERVATION="UPDATE_RESERVATION"
export const CONCLUDE_RESERVATION="CONCLUDE_RESERVATION"
export const REACTIVATE_RESERVATION="REACTIVATE_RESERVATION"


